language: python
script:
- bash -x test.sh
deploy:
  provider: releases
  api_key:
    secure: ljyVETabOJssX9T9LIh2pArGorVQNvy3moXmPDrCs5fSIKp5RiFZHX07xBOuCyI18pxw2TQ+dYUFGwYWyUfqsnGlylWBgbvBLvpZOXAua1vVwrcia/QSc9iaCT5CSRaW4KyfRmMuP16RJ0oKzhPr1jPIgxpnmTa0+cbzlBB9KjRT3dtX41eCuJRmKJm9zde7BuOS/WrvmNHk3PDTK7eSzmnZQmBbBkEvbEqpO8GF0demRvSE+7XBkwYeiYOWWbOuegGbWGIwFH3Vf9ETo8aoNMwcnhVizuNlenCzbro+S9Lt7Wfp4bKAal+ECqSg84CUc+O2OlpEb6AbZ/4rKo+8bwjWOY8sZglYUVhDbuZA2rOFHbwl+lrN8JP/EtFoGBvQg4aduVINWRr8Co2gL0KzVvnGVYwh8nHxU3/6BAW9iz8Qe0S+/LOztTAhSyZJwBHrceeInjw34plf3D38sQdYLN9zetILFLt3kFJ4OgDmwin/v7mLIoy54Kz8IBaLzBGnqA6cwocWhdE6XrrojkBFd/qTJzXf8BzmtLIUIsu2qpvlARTpp48fstKLxLl5L7AXYfelRDSZglHAOZ5YEDxOdINKn/pR3aP8CCFjl/8HuUC1t+02qp5f5ftTfQgccW5HuXDPTcxn7tSvdpteK59YIsxpSUCPZ8xmWptmsOZ/emQ=
  file: hello.sh
  on:
    repo: chavo1/hello-shell
